version: 2
general:
  branches:
    only:
     - master # list of branches to build
     - develop
     - feature/init
     - /feature-.*/ # or regexes

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.0
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run test-ci