version: '3'
services:
  app:
    build: .
    command: sh -c "cd myapp && npm install && npm rebuild node-sass && npm run start"
    volumes:
      - .:/myapp
    ports:
      - 4200:4200
  # test:
  #   build: .
  #   command: sh -c "cd mytest && npm install && npm rebuild node-sass && npm run test"
  #   volumes:
  #     - .:/mytest
  #   ports:
  #     - 9876:9876